#! /usr/bin/env bash

set -e

# Extra arguments for debug mode
if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    DEBUG_ARGS="--reload --log-level debug --timeout 5"
else
    DEBUG_ARGS=""
fi

# Provision database
# ===
FLASK_APP=webapp.app flask db upgrade

# Start server
# ===
talisker.gunicorn webapp.app:app --bind $1 --workers 3 --name talisker-$(hostname) ${DEBUG_ARGS} --timeout 30
