#! /usr/bin/env bash

set -e

# Extra arguments for debug mode
if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    DEBUG_ARGS="--reload --log-level debug --timeout 9999"
else
    DEBUG_ARGS=""
fi


# Provision database
# ===
alembic upgrade head


# Start server
# ===
talisker.gunicorn.gevent webapp.app:app --bind $1 --workers 3 --worker-class gevent --name talisker-`hostname` ${DEBUG_ARGS}

