"""empty message

Revision ID: 5df43dc932dd
Revises: c27fec1bfee2
Create Date: 2024-07-23 14:49:17.928909

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5df43dc932dd"
down_revision = "c27fec1bfee2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cve", sa.Column("numerical_id", sa.Numeric(), nullable=True)
    )
    op.create_index(
        op.f("ix_cve_numerical_id"), "cve", ["numerical_id"], unique=False
    )
    op.drop_index("notices_published_desc_idx", table_name="notice")
    op.drop_index("notices_published_idx", table_name="notice")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "notices_published_idx", "notice", ["published"], unique=False
    )
    op.create_index(
        "notices_published_desc_idx",
        "notice",
        [sa.text("published DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_cve_numerical_id"), table_name="cve")
    op.drop_column("cve", "numerical_id")
    # ### end Alembic commands ###
