"""empty message

Revision ID: c27fec1bfee2
Revises: f18a0bd8a809
Create Date: 2024-06-14 18:33:53.519236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c27fec1bfee2"
down_revision = "f18a0bd8a809"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "notices_published_desc_idx",
        "notice",
        [sa.text("published DESC")],
        unique=False,
    )
    op.create_index(
        "notices_published_idx", "notice", ["published"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("notices_published_idx", table_name="notice")
    op.drop_index("notices_published_desc_idx", table_name="notice")
    # ### end Alembic commands ###