name: Upload TICS report
on:
  push:
    branches:
      - main

jobs:
  TICS:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - run: yarn test --coverage.enabled true
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-security-api-coverage
          path: coverage
      - name: Produce TICS report
        shell: bash
        run: |
          set -x
          export TICSAUTHTOKEN=${{ secrets.TICS_AUTH_TOKEN }}
          curl --silent --show-error "https://canonical.tiobe.com/tiobeweb/TICS/api/public/v1/fapi/installtics/Script?cfg=default&platform=linux&url=https://canonical.tiobe.com/tiobeweb/TICS/" > install_tics.sh
          . ./install_tics.sh
          TICSQServer -project ubuntu-com-security-api -tmpdir /tmp/tics -branchdir .
      - name: Upload TICS report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tics-report
          path: /tmp/tics/ticstmpdir
          retention-days: 7
