name: Upload TICS report
# on:
#   push:
#     branches:
#       - main

on: pull_request

jobs:
  tics-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          python3 -m pip install --upgrade pip
          sudo pip3 install -r requirements.txt
          sudo pip3 install flake8 black coverage

      - name: Test
        run: SECRET_KEY=insecure_secret_key coverage run  --source=. -m unittest discover tests
        env:
          CI: true

      - name: Produce TICS report
        shell: bash
        run: |
          set -x
          export TICSAUTHTOKEN=${{ secrets.TICS_AUTH_TOKEN }}
          curl --silent --show-error "https://canonical.tiobe.com/tiobeweb/TICS/api/public/v1/fapi/installtics/Script?cfg=default&platform=linux&url=https://canonical.tiobe.com/tiobeweb/TICS/" > install_tics.sh
          . ./install_tics.sh
          TICSQServer -project react-components -tmpdir /tmp/tics -branchdir .

      - name: Upload TICS report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tics-report
          path: /tmp/tics/ticstmpdir
          retention-days: 7
